"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var jsx_runtime_1 = require("react/jsx-runtime");
var react_1 = require("react");
var solid_1 = require("@heroicons/react/solid");
var GitLogo = require("../assets/logos/GitLogo.png");
var LinkedinLogo = require("../assets/logos/LinkedinLogo.png");
var KaggleLogo = require("../assets/logos/KaggleLogo.png");
var MailLogo = require("../assets/logos/MailLogo.png");
var JSIcon = require("../assets/icons/JSIcon.png");
var TSIcon = require("../assets/icons/TSIcon.png");
var LeftBar = function () {
    var _a = (0, react_1.useState)(true), showWebList = _a[0], SetShowWebList = _a[1];
    var _b = (0, react_1.useState)(true), showProjectsList = _b[0], SetShowProjectsList = _b[1];
    var WebList = function () { return ((0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("a", { href: "/", children: (0, jsx_runtime_1.jsxs)("div", { className: "ml-12 flex items-center hover:cursor-pointer hover:bg-opacity-80 hover:bg-[#2b2a2a] w-60", children: [(0, jsx_runtime_1.jsx)("img", { src: JSIcon, alt: "JS Icon", className: "w-7 mr-1  ml-5 text-yellow_vs" }), (0, jsx_runtime_1.jsx)("p", { children: "First Project" })] }) }), (0, jsx_runtime_1.jsx)("a", { href: "/", children: (0, jsx_runtime_1.jsxs)("div", { className: "ml-12 flex items-center hover:cursor-pointer hover:bg-opacity-80 hover:bg-[#2b2a2a] w-60", children: [(0, jsx_runtime_1.jsx)("img", { src: TSIcon, alt: "TS Icon", className: "w-7 mr-1  ml-5 text-yellow_vs" }), (0, jsx_runtime_1.jsx)("p", { children: "Second Project" })] }) }), (0, jsx_runtime_1.jsx)("a", { href: "/", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex whitespace-nowrap items-center hover:cursor-pointer hover:bg-opacity-80 hover:bg-[#2b2a2a] focus:bg-slate-300 ml-12 w-60", children: [(0, jsx_runtime_1.jsx)("img", { src: JSIcon, alt: "JS Icon", className: "w-7 mr-1  ml-5 text-yellow_vs" }), (0, jsx_runtime_1.jsx)("p", { children: "Third Project" })] }) }), (0, jsx_runtime_1.jsx)("a", { href: "/", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex whitespace-nowrap items-center hover:cursor-pointer hover:bg-opacity-80 hover:bg-[#2b2a2a] ml-12 w-60", children: [(0, jsx_runtime_1.jsx)("img", { src: JSIcon, alt: "JS Icon", className: "w-7 mr-1  ml-5 text-yellow_vs" }), (0, jsx_runtime_1.jsx)("p", { children: "Fourth Project" })] }) })] })); };
    return ((0, jsx_runtime_1.jsx)("div", { className: "text-[#a2aabc] text-lg mt-5 flex bg-[#262526] h-full", children: (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center hover:cursor-pointer hover:bg-opacity-80 hover:bg-[#2b2a2a] font-bold w-72", onClick: function () { return SetShowProjectsList(!showProjectsList); }, children: [showProjectsList ? ((0, jsx_runtime_1.jsx)(solid_1.ChevronDownIcon, { className: "w-7 mr-1" })) : ((0, jsx_runtime_1.jsx)(solid_1.ChevronRightIcon, { className: "w-7 mr-1" })), (0, jsx_runtime_1.jsx)("p", { children: "Projects" })] }), showProjectsList ? ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center hover:cursor-pointer hover:bg-opacity-80 hover:bg-[#2b2a2a] font-bold w-72", onClick: function () { return SetShowWebList(!showWebList); }, children: [showWebList ? ((0, jsx_runtime_1.jsx)(solid_1.ChevronDownIcon, { className: "w-7 mr-1  ml-5" })) : ((0, jsx_runtime_1.jsx)(solid_1.ChevronRightIcon, { className: "w-7 mr-1  ml-5" })), (0, jsx_runtime_1.jsx)("p", { children: "Web" })] }), showWebList ? (0, jsx_runtime_1.jsx)(WebList, {}) : null] })) : null, (0, jsx_runtime_1.jsx)("div", { className: "absolute inset-x-0 bottom-10 ", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex px-6 space-x-7", children: [(0, jsx_runtime_1.jsx)("a", { href: "/", children: (0, jsx_runtime_1.jsx)("img", { src: GitLogo, alt: "Git Logo", className: "h-10 w-10 text-yellow_vs hover:cursor-pointer hover:h-12 hover:w-12" }) }), (0, jsx_runtime_1.jsx)("a", { href: "/", children: (0, jsx_runtime_1.jsx)("img", { src: KaggleLogo, alt: "Kaggle Logo", className: "h-10 w-10 text-yellow_vs hover:cursor-pointer hover:h-12 hover:w-12" }) }), (0, jsx_runtime_1.jsx)("a", { href: "/", children: (0, jsx_runtime_1.jsx)("img", { src: LinkedinLogo, alt: "Linkedin Logo", className: "h-10 w-10 text-yellow_vs hover:cursor-pointer hover:h-12 hover:w-12" }) }), (0, jsx_runtime_1.jsx)("a", { href: "/", children: (0, jsx_runtime_1.jsx)("img", { src: MailLogo, alt: "Mail Logo", className: "h-10 w-10 text-yellow_vs hover:cursor-pointer hover:h-12 hover:w-12" }) })] }) })] }) }));
};
exports.default = LeftBar;
